### ISSUE TITLE
Append prefix adds multiple copies

### ISSUE THREAD

**Issue by Zlewness** [null-dev/DynamicHistory#10]
I notice that the 'append prefix' option has been very buggy recently, it adds more than one prefix on many pages for me. Is it possible to check if the prefix already exists and stop?

Alternatively is there another way to indicate this, like changing/overlaying on the favicon, or adding styling to tab text like underlines?

**Comment by null-dev** [comment]
Yes, it is very easy for me to check if the prefix already exists and not add it if it does. But I chose not to do so as I believed if someone changed the prefix to something like `bad` and the page's title was something like `bad apples`, then the prefix would never be added. I'll make this an option in a future release.

Adding an overlay to the favicon is actually quite genius, I have never even considered doing that. I will look into that as well for a future release.

**Comment by Zlewness** [comment]
As for the prefix never being added, I was using an emoji (🚫) so it was very unlikely that it would be site added. Perhaps a unique character that only the addon can add might also help?

**Comment by null-dev** [comment]
The extension prefix is no longer prepended if the page's title starts with the prefix in the latest extension version (v2.7).
