### ISSUE TITLE
Repeating video issue

### ISSUE THREAD

**Issue by Zlewness** [null-dev/DynamicHistory#14]
I have narrowed this down to this addon, if you visit any streamable link (it was other sites too but streamable is the most obvious), the video plays over and over in the background with a delay.

Example link (warning, annoying audio): https://streamable.com/zeep3

It happens even on a new profile with only this addon enabled.

**Comment by null-dev** [comment]
Finally managed to pin down and fix this issue. The issue should be resolved in the latest release (2.11). Please re-open if it isn't! Thanks!
