### ISSUE TITLE
options not visible or not working depending versions

### ISSUE THREAD

**Issue by byblo** [null-dev/DynamicHistory#15]
Hello.
Cannot use any version above 0.2:

- If using firefox 45.0.1 (x84), options are simply not visible at all.

- If using firefox 52 (x64), option are visible, but never taken in account or saved automatically. When exporting settings, the file is almost empty.

**Comment by null-dev** [comment]
These issues should be fixed in the latest release. If they are not, please re-open this issue and I will take a closer look into this).
