### ISSUE TITLE
Visible text not detected by dangerous keyword

### ISSUE THREAD

**Issue by grenzor** [null-dev/DynamicHistory#18]
Example URL: https://github.com/null-dev/DynamicHistory/issues
Dangerous keyword: `/.*Advanced.*/` (with Regex for dangerous keywords ticked)

The page should be detected and deleted but DH doesn't detect it (even though the word Advanced is visible on the page). Only when "Scan full HTML..." is ticked does it detect the dangerous keyword.

**Comment by null-dev** [comment]
Should be fixed in latest release (2.14).
