### ISSUE TITLE
Console messages

### ISSUE THREAD

**Issue by Zlewness** [null-dev/DynamicHistory#19]
Every time I load a page this extension spams the following message:

`Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.`

In addition, sometimes I get the following spam in the console `Regex error! <unavailable>`

Finally, when I enable or disable this extension to test, I see 

`1524345671000	addons.webextension.{}	WARN	Loading extension '{}': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.`

`1524345671017	addons.webextension.{}	WARN	Please specify whether you want browser_style or not in your browser_action options.`

**Comment by null-dev** [comment]
I believe the `Unchecked lastError value` error is normal. When you load a page, it tries to update the information in the popup (to display whether or not the history is being hidden). If the popup is not open, the update will fail (but it doesn't matter as the popup is not open anyways).

The `WARN Loading extension '{}': Reading manifest ....` error is also normal. The extension is compatible with both Firefox and Chrome. Sometimes Chrome features are not available in Firefox and vice-versa so it's just warning that about that. The extension will auto-detect your browser and adapt accordingly though so it shouldn't matter.

I have no idea about the `Regex error!` though. I'll look into that.

**Comment by Zlewness** [comment]
If it helps, it triggers on the following regex, which I can't find an error with:
`/reddit\.com(.*#res:)|(.*duplicates\/)|(\/.*count=)\/$/i`

It ignores everything except the last capture group and claims `"SyntaxError: "invalid regular expression flag )"` I can trigger it with any regex using too many `\/` parts but according to the regex checkers that's valid.

**Comment by null-dev** [comment]
Alright, I've located the bug (typo caused escaped forward slashes to not be escaped). Fixing it as we speak.

I'm not sure about what you were expecting with the capture groups however. How did you expect the capture groups to be handled?

**Comment by Zlewness** [comment]
Well it was originally all in a single bracket but after it kept not escaping forward slashes I started experimenting :laughing:

**Comment by null-dev** [comment]
Alright, then I'll push the fix out as an update in a couple hours. Thanks!
