### ISSUE TITLE
Latest update broke something

### ISSUE THREAD

**Issue by grenzor** [null-dev/DynamicHistory#20]
The latest updates seems to have broken something. 

Now every page is getting detecting, using a regex like `/.*test.*/` for Dangerous keywords

**Comment by null-dev** [comment]
Just facepalmed so hard, introduced another bug while fixing a bug. Epic fail. Fixing ASAP! Sorry!

**Comment by null-dev** [comment]
This should be fixed in the latest version (2.16) now. Please  re-open if it is not.

**Comment by grenzor** [comment]
Thanks, working properly now.
