### ISSUE TITLE
Use of flags for regex

### ISSUE THREAD

**Issue by grenzor** [null-dev/DynamicHistory#5]
Please add support for flags in regex. I think the /g flag for regex will allow users to then use other flags in brackets e.g. `(?i)` for case insensitivity.

**Comment by null-dev** [comment]
Flags should work now, if they don't please re-open this issue. Example: `/something/i`

**Comment by grenzor** [comment]
Thanks, will test it out. Am I right in assuming this will support all flags e.g. `/g` `/i` `/m` and also that they can be used together like `/something/im`

**Comment by null-dev** [comment]
Yep, it support `g`, `i`, `m`, `u` and `y`. Multiple flags are supported in the way you described.
