### ISSUE TITLE
Issue with websites redirecting to https-version

### ISSUE THREAD

**Issue by hannes3120** [null-dev/DynamicHistory#6]
I think it might be similar to this issue:
https://github.com/null-dev/DynamicHistory/issues/4

Whenever a website is redirected to the https-version then the http-version isn't deleted from history
it also seems impossible to match every possible http: address since the redirect happens before the page is fully loaded and it seems as if this addon only deletes websites after they have been fully loaded

**Comment by null-dev** [comment]
The addon has been updated to begin deleting websites before they load. Hopefully that fixes this issue, please re-open if it doesn't!
