### ISSUE TITLE
Option for keywords to delete from search bar suggestions

### ISSUE THREAD

**Issue by grenzor** [null-dev/DynamicHistory#7]
It would great to have to ability to delete keywords that show up as suggestions in the search bar. When you type something e.g. `github` in the search bar and search it the next time you type a few letters `git` into the search bar it will show `github` in dropdown suggestions. Option to set dangerous keywords (separately from those for pages) for search bar suggestions would be useful.

**Comment by null-dev** [comment]
I've looked a bit into this and I can't find any way to modify search suggestions from an extension so it looks like I won't be able to implement this. Sorry.

**Comment by grenzor** [comment]
Ah ok, hopefully as Firefox's Webextension APIs mature it will become possible.
